### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by v-alje**
Build.Reason:Manual by Alma Jenks
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=332132&view=results
 source_repo.branch:master
 source_repo.csvPath:bundlepackages/efcore
 source_repo.url:https://apidrop.visualstudio.com/binaries/_git/mrefconfig

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
These namespaces should be hidden:

- Microsoft.EntityFrameworkCore.Cosmos.ChangeTracking.Internal
- Microsoft.EntityFrameworkCore.Cosmos.Design.Internal
- Microsoft.EntityFrameworkCore.InMemory.Design.Internal
- Microsoft.EntityFrameworkCore.SqlServer.Extensions.Internal

**Comment by v-alje** [comment]
@AndriySvyryd The namespaces have been added to the _filter.xml file so they won't build.

**Review by AndriySvyryd — APPROVED** [review]
Are you also going to merge this to live?

**Comment by v-alje** [comment]
@AndriySvyryd Yes. Through main.

**Pull request merged**
