### PR TITLE
Add products taxonomy to improve findability

### PR DESCRIPTION
**Pull request by kenanlv**
Adds docs products taxonomy to the repo to improve findability experiences (onsite search, recommendations and others)

| Product Label      | Products |
| ----------- | ----------- |
| .NET      | https://authoring-docs-microsoft.poolparty.biz/devrel/7696cda6-0510-47f6-8302-71bb5d2e28cf       |
| .NET Core   | https://authoring-docs-microsoft.poolparty.biz/devrel/75c493a7-abb6-4435-a651-8d9450a8ce66        |
| ASP.NET Core   | https://authoring-docs-microsoft.poolparty.biz/devrel/d452572f-6212-498f-9050-ca4a9e50a425        |
| ASP.NET   | https://authoring-docs-microsoft.poolparty.biz/devrel/8eb81391-e81d-4461-aa4a-9512fd4bbed8        |
| Entity Framework Core   | https://authoring-docs-microsoft.poolparty.biz/devrel/56a03cf0-cabf-4e70-800b-dcb9ff39361c        |
| Entity Framework 6.0   | https://authoring-docs-microsoft.poolparty.biz/devrel/813ee603-b1aa-4b7d-b96b-32a5a254748a       |

### CODE REVIEW

**Comment by kenanlv** [comment]
@sudeepku Hello, here is the product taxonomy update.

**Comment by sudeepku** [comment]
@JeremyLikness , @ajcvickers - updates per discussion over email.
we will keep the PR open till Friday when we can update the config for Entity Framework 6.0 too.
@kenanlv - please add prefix DO NOT MERGE to the PR title.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.ApiDocs?pullRequest=97) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.ApiDocs?pullRequest=97) before we can accept your contribution.<br/><br/>:x: kenanlv [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.ApiDocs?pullRequest=97)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.ApiDocs?pullRequest=97) it.</sub>

**Comment by sudeepku** [comment]
@ajcvickers , @JeremyLikness , @rloutlaw - could one of you merge this PR to master and then merge the changes to live.
updates align with our discussion over email.

**Comment by smitpatel** [comment]
@ajcvickers @JeremyLikness - I can process the change if PR looks good. I am not part of the email discussion so need approval from someone who knows.

**Review by JeremyLikness — APPROVED** [review]
@smitpatel I approve.

**Pull request merged**
